In [1]:
#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [3]:
import numpy as np

In [31]:
r = np.array(revenue)
r = np.round(r, 2)
e = np.array(expenses)
e = np.round(e, 2)

array([14574.49,  7606.46,  8611.41,  9175.41,  8058.65,  8105.44,
       11496.28,  9766.09, 10305.32, 14379.96, 10713.97, 15433.5 ])

In [32]:
profit_for_each_month = r - e
np.around(profit_for_each_month, 2)

array([ 2522.67,  1911.39, -3707.79, -2914.31,  -599.92,  7265.24,
        8210.55,  3944.97,  3328.39, -2238.65,   659.6 , 11629.54])

In [34]:
profit_after_tax = (r * 0.7) - e
np.around(profit_after_tax, 2)

array([-1849.68,  -370.55, -6291.21, -5666.93, -3017.52,  4833.61,
        4761.67,  1015.14,   236.79, -6552.64, -2554.59,  6999.49])

In [63]:
profit_margin_per_month = profit_after_tax/e
profit_margin = np.around(profit_margin_per_month, 2)
profit_margin

array([-0.15, -0.07, -0.51, -0.47, -0.35,  5.75,  1.45,  0.17,  0.03,
       -0.39, -0.25,  1.84])

In [38]:
mean = profit_after_tax.mean()
np.around(mean, 2)

-704.7

In [39]:
good_months = profit_after_tax > mean
good_months

array([False,  True, False, False, False,  True,  True,  True,  True,
       False, False,  True])

In [40]:
bad_months = profit_after_tax < mean
bad_months

array([ True, False,  True,  True,  True, False, False, False, False,
        True,  True, False])

In [41]:
best_month = profit_after_tax.max()
np.around(best_month, 2)

6999.49

In [42]:
worst_month = profit_after_tax.min()
np.around(worst_month, 2)

-6552.64

In [57]:
import locale
locale.setlocale( locale.LC_ALL, 'en_CA.UTF-8' )
profit_formated = [locale.currency(a, grouping=True)[:-3] for a in profit_after_tax]
profit_formated

['-$1,849',
 '-$370',
 '-$6,291',
 '-$5,666',
 '-$3,017',
 '$4,833',
 '$4,761',
 '$1,015',
 '$236',
 '-$6,552',
 '-$2,554',
 '$6,999']

In [65]:
profit_margin_formated = [str((a * 100).round(0))[:-2] + '%' for a in profit_margin]
profit_margin_formated

['-15%',
 '-7%',
 '-51%',
 '-47%',
 '-35%',
 '575%',
 '145%',
 '17%',
 '3%',
 '-39%',
 '-25%',
 '184%']